repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=10000']  # Allow larger files for models
    -   id: debug-statements
    -   id: detect-private-key
    -   id: check-merge-conflict
    -   id: check-json
    -   id: pretty-format-json
        args: ['--autofix']
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args: ['--line-length=131']
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: ['--max-line-length=131', '--ignore=E203,W503,E501']
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
    -   id: autoflake
        args: ["--remove-all-unused-imports", "--remove-unused-variables", "--in-place"]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--line-length=131"]
